name: Publish MASTER Docker image

on:
  push:
    branches:
      - master

jobs:
  build-master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        build-args: VERSION=${{ github.sha }}
        tags: shakapark/clamav-prometheus-exporter:latest